### ISSUE TITLE
Get-3parCage -CageName cage

### ISSUE THREAD

**Issue by TharunikaJVR** [HewlettPackard/hpe3par_pstoolkit#10]
If we are passing wrong parameter the expected result should throw Failure.
Ex: Get -3parCage –CageName cage3543
Expected : Failure 
Actual Result : Yes throwing Failure.
Result : Working as expected.

But Here if we pass the keyword cage as parameter  it is returning Success.
Ex : Get -3parCage –CageName cage 
Expected : Should throw a Failure 
Actual Result : RETURNING SUCCESS 
Result : Not  Working as expected.
![Bug_CageName](https://user-images.githubusercontent.com/50730980/57907687-ca408200-789b-11e9-8aa4-b838882dd81a.png)

**Comment by Mohd-Aslam-Shaikh** [comment]
Resolved..

**Comment by harikumar-r** [comment]
Please use Get-Cage cmdlet
