### ISSUE TITLE
support matrix need an update

### ISSUE THREAD

**Issue by prablr79** [HewlettPackard/hpe3par_pstoolkit#2]
There seems to be something incorrect with the supported Storage platform below (on the dev portal). Shouldn’t it be 3.3.1, 3.2.2, 3.2.1, etc?

HPE 3PAR StoreServ 7000, 8000, 10000, and 20000 series.
Supported firmware for HPE 3PAR StoreServ Storage are:
•	3.1 (MU1, MU2, MU3 & MU4)
•	3.1 (MU1, MU2, and MU3)
•	2.2 (including all MUs)
•	2.1 (including all MUs)

**Comment by harikumar-r** [comment]
Review the whole Readme.md file and fixed the typos.
