### ISSUE TITLE
What type of connection shall i use when starting now

### ISSUE THREAD

**Issue by weidi** [HewlettPackard/hpe3par_pstoolkit#29]
At the moment it seems that there are three different Options on how to connect to 3Par / Primera.
1. 3parCLI
2. POSH
3. WSAPI

Is there one target you are heading and what will it be if so?
Just asking as object piping seems only be supported when using 3parcli like

PS > Get-3parvv | Remove-3parvv
FAILURE : Invalid cli type

I try to keep dependencys as low as possible and tried using POSH method

**Comment by harikumar-r** [comment]
You can use New-PoshSSHConnection/New-CLIConnection cmdlet to connect the 3par/Primera/Alletra
And another option is to use New-WSAPIConnection cmdlet to connect the 3par/Primera/Alletra
