### ISSUE TITLE
Powershell Took kit example commands not working

### ISSUE THREAD

**Issue by rajubellamkonda** [HewlettPackard/hpe3par_pstoolkit#8]
Hi All,
i am using the 3PAR powershell toolkit and running following which is in the example list and it doesnt seem to work

tried several of such commands from pwoershell toolkit and examples, looks like compareby or NoofRecords doesnt seem to work. has anyone used this ?

example from the toolkit:

-------------------------- EXAMPLE 10 --------------------------
PS C:\>Get-3PARCacheMemoryStatisticsDataReports_WSAPI -VersusTime -Frequency_Hires -Compareby top -NoOfRecords 2 -ComparebyField hitIORead

error when we run on system:

C:\HPE3PARPSToolkit> Get-3PARCacheMemoryStatisticsDataReports_WSAPI -VersusTime -Frequency_Hires -Compareby top -NoOfRecords 2 -ComparebyField onlyCompareby
URL = /systemreporter/vstime/cachememorystatistics/hires;compareby:top,2,onlyCompareby
The array send an error message: Invalid system reporter parameter name or its value.

Status: ProtocolError
Error code: 296
HTTP Error code: 400
Message: Invalid system reporter parameter name or its value

FAILURE : While Execute Get-3PARCacheMemoryStatisticsDataReports_WSAPI.

**Comment by harikumar-r** [comment]
Please let me know whether this cmdlet execution works
Get-CacheMemoryStatisticsDataReports_WSAPI -VersusTime -Frequency_Hires -Compareby top -NoOfRecords 2 -ComparebyField hitIORead
